version: '2'
services:
  mongo:
    image: mongo:4
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # volumes:
    # - ./data/db:/data/db
    ports:
      - '27017:27017'
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
  graphql-server:
    build: .
    container_name: 'graphql-server'
    ports:
      - '4000:4000'
    links:
      - mongo
    depends_on:
      - mongo
